#
# Generated by the NeXT Project Builder.
#
# NOTE: Do NOT change this file -- Project Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = QuakeEd

PROJECTVERSION = 1.1
LANGUAGE = English

APPICON = i_quakeed.tiff
LOCAL_RESOURCES = QuakeEd.nib

GLOBAL_RESOURCES = DownArrow.tiff i_90d.tiff i_add.tiff i_brushes.tiff\
                   i_fliph.tiff i_flipv.tiff i_quakeed.tiff i_sub.tiff\
                   short.tiff tall.tiff UpArrow.tiff

CLASSES = CameraView.m Clipper.m Dict.m DictList.m Entity.m\
          EntityClass.m InspectorControl.m KeypairView.m Map.m\
          PopScrollView.m Preferences.m Project.m QuakeEd.m SetBrush.m\
          TexturePalette.m TextureView.m Things.m UserPath.m XYView.m\
          ZScrollView.m ZView.m

HFILES = CameraView.h Clipper.h Dict.h DictList.h Entity.h\
         EntityClass.h InspectorControl.h KeypairView.h Map.h\
         PopScrollView.h Preferences.h Project.h QuakeEd.h SetBrush.h\
         TexturePalette.h TextureView.h Things.h UserPath.h XYView.h\
         ZScrollView.h ZView.h render.h cmdlib.h mathlib.h

MFILES = misc.m QuakeEd_main.m render.m

CFILES = cmdlib.c mathlib.c

OTHERSRCS = Makefile.preamble Makefile Makefile.postamble


MAKEFILEDIR = /NextDeveloper/Makefiles/app
MAKEFILE = app.make
INSTALLDIR = /LocalApps
INSTALLFLAGS = -c -s -m 755
SOURCEMODE = 444

ICONSECTIONS =	-sectcreate __ICON app i_quakeed.tiff

LIBS = -lMedia_s -lNeXT_s
DEBUG_LIBS = $(LIBS)
PROF_LIBS = $(LIBS)




-include Makefile.preamble

include $(MAKEFILEDIR)/$(MAKEFILE)

-include Makefile.postamble

-include Makefile.dependencies
